#!/usr/bin/env python3
"""Generate self-contained editor adapters from canonical reference files."""
from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
SOURCES = (ROOT / "reference" / "methodology.md", ROOT / "reference" / "check-families.md")
TARGETS = {
    "codex-instructions.md": ("<!-- DISSECT-START -->", "<!-- DISSECT-END -->", "Codex/AGENTS.md"),
    "cursor-rules.md": ("", "", "Cursor"),
    "generic-instructions.md": ("", "", "generic AI editor"),
}


def canonical_body() -> tuple[str, str]:
    parts = [source.read_text(encoding="utf-8").strip() for source in SOURCES]
    body = "\n\n---\n\n".join(parts)
    digest = hashlib.sha256(body.encode("utf-8")).hexdigest()
    return body, digest


def render(start: str, end: str, label: str) -> str:
    body, digest = canonical_body()
    header = (
        f"<!-- GENERATED by scripts/sync_adapters.py for {label}; do not edit. -->\n"
        f"<!-- canonical-sha256: {digest} -->\n"
    )
    content = header + body + "\n"
    if start:
        content = f"{start}\n{content}{end}\n"
    return content


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for filename, spec in TARGETS.items():
        target = ROOT / "adapters" / filename
        expected = render(*spec)
        if args.check:
            if not target.exists() or target.read_text(encoding="utf-8") != expected:
                stale.append(target.relative_to(ROOT).as_posix())
        else:
            target.write_text(expected, encoding="utf-8")
    if stale:
        print("Adapter drift detected: " + ", ".join(stale), file=sys.stderr)
        print("Run: python3 scripts/sync_adapters.py", file=sys.stderr)
        return 1
    if not args.check:
        print("Generated adapters from canonical methodology and check families.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
